[package]
name = "adventofcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
muldiv = "1.0.1"
num = "0.4.1"

[[bin]]
name = "adventofcode"
path = "src/main.rs"
